version: "3.8"
services:
  postgres:
    image: postgres
    volumes: 
      - data:/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: ./stopwatch-api
    ports:
      - '80:80'
    depends_on:
      - postgres
  web:
    build: ./stopwatch-web
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - api 

volumes: 
  data: